# List of playbooks to include on the Playbooks page in additon to the
# CTO-produced playbooks located in the /_playbooks/ folder.

- title: Identity Playbook
  description: Login.gov's playbook on identity management.
  url: https://www.login.gov/playbook/

- title: Digital Services Playbook
  description: US Digital Services playbook to help government build effective digital services.
  url: https://playbook.cio.gov/

- title: 18F Guides
  description: 18F provides a repository of best practices across their teams.
  url: https://guides.18f.gov/

- title: 18F Partnership Principles
  description: 18F's approach to collaboration with agencies that have partnerships with 18F.
  url: https://18f.gsa.gov/partnership-principles/

- title: 18F Automated Testing Playbook
  description: A set of principles, practices, idioms, and strategies pertaining to automated software testing and its adoption.
  url: https://18f.github.io/automated-testing-playbook/

- title: Technology Business Management Playbook
  description: This playbook is designed to assist federal agencies as they start Technology Business Management (TBM) implementation. While each agency should tailor its TBM implementation to their organization’s current state and desired outcomes, the playbook offers guidance and lessons learned from the U.S. General Services Administration (GSA) and the U.S. Department of Education.
  url: ../assets/downloads/GSA_Education_TBM_Playbook_v6.pdf
