# CTO Projects List

- name: TechTalks
  contact_name: Office of the CTO
  contact_email: cto@gsa.gov
  link: techtalks/
  picture: project_tech.gsa.gov.jpg
  description: GSA IT provided technology deep dives. There are many opportunties for GSA employees to participate in upcoming events. You can look through slides are available for most past events.

- name: Data Science Practitioner Training
  contact_name: Sara Cope
  contact_email: sara.cope@gsa.gov
  link: data-science/
  picture: project_open.gsa.gov.png
  description: Description of the program.
