# CTO Projects List

- name: TechTalks
  contact_name: Office of the CTO
  contact_email: cto@gsa.gov
  link: techtalks/
  picture: project_tech.gsa.gov.jpg
  description: GSA IT provided technology deep dives available to all employees. There are many opportunties for GSA employees to participate in upcoming events. Slides are available for most past events.

- name: Data Science Practitioner Training
  contact_name: Sara Cope
  contact_email: sara.cope@gsa.gov
  link: data-science/
  picture: project_open.gsa.gov.png
  description: Data science is a concept to unify statistics, data analysis and their related methods in order to understand and analyze actual phenomena with data.
